apiVersion: v1
kind: ConfigMap
metadata:
  name: backup-config
data:
  RESOURCE_KINDS: "secrets"
  GPGKEY: "public.pgp"
  UPLOAD: "true"
  BUCKET: dev-artifact-backup
  KEEPFOR: "30"
  VERIFYSSL: "/certs/cacert.pem"
  ENDPOINT: "https://s3-eu-central-2.ionoscloud.com"
  REGION: "eu-central-2"
