apiVersion: batch/v1
kind: CronJob
metadata:
  name: kube-artifact-backup
spec:
  schedule: "0 0 * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: kube-artifact-backup
              image: docker.io/1and1internet/kube-artifact-backup
              imagePullPolicy: IfNotPresent
              envFrom:
                - secretRef:
                    name: s3_credentials
                - configMapRef:
                    name: backup-config
              volumeMounts:
                - name: certs
                  mountPath: /certs
          volumes:
            - name: certs
          restartPolicy: OnFailure
