apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: cert-manager
spec:
  groups:
  - name: cert-manager
    rules:
    - alert: CronjobSuspended
        expr: kube_cronjob_spec_suspend != 0
      for: 1h
      labels:
        severity: warning
      annotations:
        summary: Kubernetes CronJob suspended (instance {{ $labels.instance }})
        description: "CronJob {{ $labels.namespace }}/{{ $labels.cronjob }} is suspended\n  VALUE = {{ $value }}\n  LABELS = {{ $labels }}"
    - alert: CronJobStatusFailed
        expr: |
          job_cronjob:kube_job_status_failed:sum
          * ON(cronjob) GROUP_RIGHT()
          kube_cronjob_labels{cronjob="kube-artifact-backup"}
          > 0
        for: 6h
        annotations:
          description: '{{ $labels.cronjob }} last run has failed {{ $value }} times.'
