---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: artifact-backup
  labels:
    app: artifact
    component: backup
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: secret-reader
rules:
#- apiGroups: ["rbac.authorization.k8s.io"]
- apiGroups: [""]
  resources:
    - secrets
  verbs:
    - get
    - watch
    - list
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: artifact-backup-secret-reader
roleRef:
  #apiGroup: rbac.authorization.k8s.io
  apiGroup: ""
  kind: ClusterRole
  name: secret-reader
subjects:
  - kind: ServiceAccount
    name: artifact-backup
    namespace: artifact-backup
